import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  Loader2,
  RefreshCw,
  Terminal,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Play,
} from "lucide-react";
import { runProject, TerminalOutput } from "../services/webcontainer";
import { FileStructure } from "../Types";

// ────────────────────────────────────────────
// Props
// ────────────────────────────────────────────

interface PreviewFrameProps {
  /** The complete file tree generated by the LLM */
  fileStructure: FileStructure;
  /** True while the LLM is still streaming files */
  isStreaming: boolean;
}

// ────────────────────────────────────────────
// Component
// ────────────────────────────────────────────

type PreviewStatus =
  | "idle"
  | "booting"
  | "mounting"
  | "installing"
  | "starting"
  | "ready"
  | "error";

const statusLabel: Record<PreviewStatus, string> = {
  idle: "Waiting for files…",
  booting: "Booting WebContainer…",
  mounting: "Mounting project files…",
  installing: "Installing dependencies…",
  starting: "Starting dev server…",
  ready: "Preview ready",
  error: "Something went wrong",
};

const PreviewFrame: React.FC<PreviewFrameProps> = ({
  fileStructure,
  isStreaming,
}) => {
  const [status, setStatus] = useState<PreviewStatus>("idle");
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [logs, setLogs] = useState<TerminalOutput[]>([]);
  const [showTerminal, setShowTerminal] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const teardownRef = useRef<(() => void) | null>(null);
  const logsEndRef = useRef<HTMLDivElement>(null);
  const hasRunRef = useRef(false);

  // Auto-scroll terminal
  useEffect(() => {
    logsEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  const addLog = useCallback((output: TerminalOutput) => {
    setLogs((prev) => [...prev, output]);

    // Update status based on log content (strip ANSI first)
    const t = stripAnsi(output.text).toLowerCase();
    if (t.includes("mounting")) setStatus("mounting");
    else if (t.includes("installing")) setStatus("installing");
    else if (t.includes("starting dev")) setStatus("starting");
    else if (t.includes("server ready") || t.includes("ready in")) setStatus("ready");
  }, []);

  const launch = useCallback(async () => {
    // Need at least a package.json to run
    if (!fileStructure || !Object.keys(fileStructure).length) return;
    if (
      !("package.json" in fileStructure) &&
      !hasNestedPackageJson(fileStructure)
    ) {
      setStatus("idle");
      return;
    }

    // Cleanup previous run
    teardownRef.current?.();
    setPreviewUrl(null);
    setErrorMsg(null);
    setLogs([]);
    setStatus("booting");

    try {
      const { urlPromise, teardown } = await runProject(fileStructure, addLog);
      teardownRef.current = teardown;
      const url = await urlPromise;
      setPreviewUrl(url);
      setStatus("ready");
    } catch (err) {
      console.error("Preview launch error:", err);
      setErrorMsg(err instanceof Error ? err.message : String(err));
      setStatus("error");
    }
  }, [fileStructure, addLog]);

  // Auto-launch once streaming finishes and we have files
  useEffect(() => {
    if (
      !isStreaming &&
      Object.keys(fileStructure).length > 0 &&
      !hasRunRef.current
    ) {
      hasRunRef.current = true;
      launch();
    }
  }, [isStreaming, fileStructure, launch]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      teardownRef.current?.();
    };
  }, []);

  // ─── Render ───────────────────────────────

  return (
    <div className="flex flex-col h-full bg-[#0A0A0A]">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-3 py-2 bg-[#111111] border-b border-gray-800 text-sm">
        <div className="flex items-center gap-2 text-gray-400">
          {status === "ready" ? (
            <span className="inline-block w-2 h-2 rounded-full bg-green-500" />
          ) : status === "error" ? (
            <span className="inline-block w-2 h-2 rounded-full bg-red-500" />
          ) : status !== "idle" ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin text-yellow-500" />
          ) : null}
          <span>{statusLabel[status]}</span>
        </div>

        <div className="flex items-center gap-1">
          {/* Re-run */}
          <button
            onClick={() => {
              hasRunRef.current = false;
              launch();
            }}
            disabled={
              isStreaming || status === "booting" || status === "installing"
            }
            className="p-1.5 rounded hover:bg-gray-800 text-gray-400 hover:text-white disabled:opacity-40 transition"
            title="Re-run project"
          >
            {status !== "idle" && status !== "ready" && status !== "error" ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <RefreshCw className="w-4 h-4" />
            )}
          </button>

          {/* Open in new tab */}
          {previewUrl && (
            <a
              href={previewUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="p-1.5 rounded hover:bg-gray-800 text-gray-400 hover:text-white transition"
              title="Open in new tab"
            >
              <ExternalLink className="w-4 h-4" />
            </a>
          )}

          {/* Toggle terminal */}
          <button
            onClick={() => setShowTerminal((v) => !v)}
            className={`p-1.5 rounded hover:bg-gray-800 transition ${showTerminal ? "text-yellow-500" : "text-gray-400 hover:text-white"}`}
            title="Toggle terminal"
          >
            <Terminal className="w-4 h-4" />
            {showTerminal ? (
              <ChevronDown className="w-3 h-3 inline ml-0.5" />
            ) : (
              <ChevronUp className="w-3 h-3 inline ml-0.5" />
            )}
          </button>
        </div>
      </div>

      {/* Preview area */}
      <div className="flex-1 relative">
        {status === "ready" && previewUrl ? (
          <iframe
            src={previewUrl}
            className="w-full h-full border-0"
            title="Live Preview"
            sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-modals"
          />
        ) : status === "error" ? (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-gray-400">
            <div className="text-red-400 text-center max-w-md">
              <p className="text-lg font-medium mb-2">Build failed</p>
              <p className="text-sm">{errorMsg}</p>
            </div>
            <button
              onClick={() => {
                hasRunRef.current = false;
                launch();
              }}
              className="flex items-center gap-2 px-4 py-2 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 transition"
            >
              <RefreshCw className="w-4 h-4" />
              Retry
            </button>
          </div>
        ) : status === "idle" && !isStreaming ? (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-gray-500">
            {Object.keys(fileStructure).length > 0 ? (
              <button
                onClick={() => {
                  hasRunRef.current = false;
                  launch();
                }}
                className="flex items-center gap-2 px-5 py-2.5 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 transition"
              >
                <Play className="w-4 h-4" />
                Run Preview
              </button>
            ) : (
              <p>Waiting for generated files…</p>
            )}
          </div>
        ) : (
          /* Loading states */
          <div className="flex flex-col items-center justify-center h-full gap-3 text-gray-400">
            <Loader2 className="w-8 h-8 animate-spin text-yellow-500" />
            <p className="text-sm">{statusLabel[status]}</p>
          </div>
        )}
      </div>

      {/* Terminal panel */}
      {showTerminal && (
        <div className="h-48 border-t border-gray-800 bg-[#0d0d0d] overflow-y-auto font-mono text-xs p-3">
          {logs.map((log, i) => (
            <div
              key={i}
              className={`whitespace-pre-wrap ${
                log.type === "error"
                  ? "text-red-400"
                  : log.type === "stderr"
                    ? "text-yellow-400"
                    : log.type === "info"
                      ? "text-blue-400"
                      : "text-gray-300"
              }`}
            >
              {stripAnsi(log.text)}
            </div>
          ))}
          <div ref={logsEndRef} />
        </div>
      )}
    </div>
  );
};

// ────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────

/** Strip ANSI escape codes from terminal output */
function stripAnsi(text: string): string {
  // eslint-disable-next-line no-control-regex
  return text.replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g, "");
}

function hasNestedPackageJson(structure: FileStructure): boolean {
  for (const value of Object.values(structure)) {
    if (typeof value === "string") continue;
    if ("package.json" in value) return true;
    if (hasNestedPackageJson(value as FileStructure)) return true;
  }
  return false;
}

export default PreviewFrame;
